env:
    browser: true
    es2021: true
ignorePatterns:
    - '**/*.js'
    - 'vite.config.ts'
extends:
    - 'airbnb'
    - 'airbnb/hooks'
    - 'airbnb-typescript'
    - 'prettier'
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaVersion: 'latest'
    sourceType: 'module'
    project: './tsconfig.json'
plugins:
    - '@typescript-eslint'
rules:
    'class-methods-use-this': off
    'react/react-in-jsx-scope': off
